spring:
  application:
    name: Configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hRJ06/Spring-Config-Server
          username: hRJ06
          password:
          default-label: main
server:
    port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
