apiVersion: v1
kind: Pod
metadata:
  name: test-nginx-pod
  labels:
    name: myapp
    env: dev
spec:
  containers:
  - name: test-nginx-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
