#jwt:
#  secret_key: P9bRq8c3ZjTNz7XLM5vJHyWcS4dGQ5Ef

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8888
#API Gateway Configuration
#  cloud:
#    gateway:
#      routes:
#        - id: Order-Service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/api/v1/orders/**
##            - Method=GET,POST
#          filters:
#            - StripPrefix=2
##            - RedirectTo=302, https://app.codingshuttle.com/
#            - name: LoggingOrdersFilter
#            - name: Authentication
#              args:
#                isEnabled: false
##                   No need to explicitly write full name when GatewayFilterFactory is a suffix
#        - id: Inventory-Service
#          uri: lb://INVENTORY-SERVICE
#          predicates:
#            - Path=/api/v1/inventory/**
#          filters:
#            - StripPrefix=2
#            - AddRequestHeader=X-Custom-Header, Hindol
#            - name: Authentication
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka