spring:
  application:
    name: api-gateway

#API Gateway Configuration
  cloud:
    gateway:
      routes:
        - id: Order-Service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
#            - Method=GET,POST
          filters:
            - StripPrefix=2
#            - RedirectTo=302, https://app.codingshuttle.com/
        - id: Inventory-Service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Hindol

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka