apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: hrj06/ecommerce-inventory
        resources:
          limits:
            memory: "400Mi"
            cpu: "200m"
          requests:
            memory: "200Mi"
            cpu: "100m"
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_USER

          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_PASSWORD

          - name: DB_SERVICE
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: INVENTORY_DB_SERVICE

          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: my-secret
                key: INVENTORY_DB_NAME
        ports:
        - containerPort: 9010


--- 
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 9010